brazilian_sales:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: apc-data-science-and-ai
      dataset: brazilian_sales
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      ##keyfile: /home/eugen/ProjectM2/meltano-bigquery-py311/apc-data-science-and-ai-1c8f5b9e267b.json
    prod:
      type: bigquery
      method: service-account
      project: apc-data-science-and-ai
      dataset: brazilian_sales_prod
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      ##keyfile: /home/eugen/ProjectM2/meltano-bigquery-py311/apc-data-science-and-ai-1c8f5b9e267b.json