olist_transform:
  outputs:
    dev:
      dataset: olist_raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/azni/.google/dsai-group.json
      location: US
      method: service-account
      priority: interactive
      project: dsai-group
      threads: 4
      type: bigquery
  target: dev
