version: 2

models:
  - name: stg_orders
    description: Cleaned orders data
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']

  - name: stg_customers
    description: Cleaned customers data
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Cleaned products data
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    description: Cleaned sellers data
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null
