name: 'brazilian_ecommerce_analytics'
version: '2.0.0'
config-version: 2

profile: 'brazilian_ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  brazilian_ecommerce_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

tests:
  brazilian_ecommerce_analytics:
    +severity: warn
